### ISSUE TITLE
similarityGroups function not in npm

### ISSUE THREAD

**Issue by alexhwoods** [deestan/set-clustering#3]
Anyway we could get you guys to update the library in npm, containing the similarityGroups function? I'd argue that's probably the most useful function in this library

**Comment by alexhwoods** [comment]
For other people who encounter this problem, it's best just to install the library directly from Github.

Using yarn (npm would work too):
`yarn add https://github.com/deestan/set-clustering.git`

**Comment by silviuburceadev** [comment]
@deestan any chance you'd publish a v1.0.2 to npm to include this feature?

@alexhwoods 
> 
> 
> For other people who encounter this problem, it's best just to install the library directly from Github.
> 
> Using yarn (npm would work too):
> `yarn add https://github.com/deestan/set-clustering.git`

This doesn't play too nice when you're behind a corporate proxy unfortunately. It can work, but it's a bit messy.

**Comment by helgeholm** [comment]
I am unlikely to release any updates to this project, so I will encourage
you to fork and release a successor.

**Comment by silviuburceadev** [comment]
@deestan For this issue in particular, it would be as easy as bump the version to 1.1.0(in line with semver, since a new feature is introduced) and `npm publish`. 

Would you like someone to take care of the releases for this repo? Even if I fork it, I can't release a new version on npm for `set-clustering` unless you add me on npm as owner for the module and eventually as a contributor to this repo so I can make the changes myself and not bother you.

**Comment by helgeholm** [comment]
Thanks for the offer. :) I've added you as a contributor here and (at least someone with the same name) as maintainer on NPM.

**Comment by silviuburceadev** [comment]
@alexhwoods @GabiAxel I have merged #4 and published set-clustering 1.1.0 on NPM today, which includes `similarGroups` function.
